#!/usr/bin/env perl

use strict;
use warnings;
use Getopt::Long qw(:config pass_through no_ignore_case);

my ($delimiter, $lines) = ("\t",4);

GetOptions (
  "delimiter:s" => \$delimiter,
  "lines:i"  => \$lines,
);

while (<>) {
    chomp;
    print $_ . ($. % $lines ? $delimiter : "\n")
}